-- task_2.sql
-- Create all tables for the ALX Book Store schema

USE alx_book_store;

-- AUTHORS
CREATE TABLE IF NOT EXISTS AUTHORS (
  author_id INT PRIMARY KEY,
  author_name VARCHAR(215) NOT NULL
) ENGINE=INNODB;

-- BOOKS
CREATE TABLE IF NOT EXISTS BOOKS (
  book_id INT PRIMARY KEY,
  title VARCHAR(130) NOT NULL,
  author_id INT NOT NULL,
  price DOUBLE,
  publication_date DATE,
  CONSTRAINT FK_BOOKS_AUTHOR
    FOREIGN KEY (author_id) REFERENCES AUTHORS(author_id)
) ENGINE=INNODB;

-- CUSTOMERS
CREATE TABLE IF NOT EXISTS CUSTOMERS (
  customer_id INT PRIMARY KEY,
  customer_name VARCHAR(215) NOT NULL,
  email VARCHAR(215),
  address TEXT
) ENGINE=INNODB;

-- ORDERS
CREATE TABLE IF NOT EXISTS ORDERS (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_date DATE,
  CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id)
) ENGINE=INNODB;

-- ORDER_DETAILS
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
  orderdetailid INT PRIMARY KEY,
  order_id INT NOT NULL,
  book_id INT NOT NULL,
  quantity DOUBLE,
  CONSTRAINT FK_OD_ORDER
    FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),
  CONSTRAINT FK_OD_BOOK
    FOREIGN KEY (book_id) REFERENCES BOOKS(book_id)
) ENGINE=INNODB;
